---
title: "Expriments for Trust"
author: "Group"
output:
  pdf_document: default
  html_document: default
---

```{r}
library(ggplot2)
library(ggthemr)
library(dplyr)
```

```{r}
# Load the expriment's data
dlu <- read.csv("./cleaneddata/lucid.csv")
head(dlu)
``` 
```{r}
dlu$Outcome <- ifelse(dlu$Q7=="I do not trust what the speaker was saying.", "No Trust", ifelse(dlu$Q7=="I trust what the speaker was saying.", "Trust", "NA"))

summary(dlu)
```


```{r}
ggthemr('earth', type="outer", layout='scientific', spacing=2)

p3 <- ggplot(data=dlu %>% filter(Outcome != "NA"), aes(x=FL_3_DO)) +
  geom_bar(aes(y=FL_3_DO, fill=Outcome), stat = "identity") +
  labs(title="Counts", y="Total Counts", x = "Tmt vs. Control") +
  ylab("") +
  theme_classic() #+ theme(legend.position = "none")

p3
```

```{r}
# Adding columns for control, treatment and clusters (M, F)
t = c("FTreatment", "MTreatment")
s = c("FTreatment", "FControl")
dlu$treat = ifelse(dlu$FL_3_DO %in% t, 1, 0 )
dlu$female = ifelse(dlu$FL_3_DO %in% s, 1, 0)
dlu$trust = ifelse(dlu$Q7 == "I trust what the speaker was saying.", 1,
                   ifelse (dlu$Q6 != "Pritikin" | dlu$Q7 == "", NA, 0))
```
```{r}
head(dlu, 100)
```
```{r}
summary(dlu)
```
```{r}
# Distribution of treatment vs control
hist(dlu$treat, main='Distribution of treatment, 1 is treatment', xlab='Treatment')
```
```{r}
# Distribution of male vs female
hist(dlu$female, main='Gender Distribution', xlab='Gender, 1 is female')
```
**These distributions are fine**
```{r}
# Regressing trust on treatment
lrmt = lm(trust ~ treat, data = dlu)
summary(lrmt)
```
```{r}
ate = lrmt$coefficients['treat']
paste0('The ATE of the dissonace video is: ', ate)
```


```{r}
# Adding Female as the covariate
lrmt1 = lm(trust ~ treat + female * treat, data = dlu)
summary(lrmt1)
```


```{r}
# Randomization inference
# Creating new variables for randomizing run and run_lag
dlu$treat_rnd = sample(dlu$treat)
head(dlu)
summary(dlu)
```
```{r}
# Repeating the regression with the randomized treatment variable
# Regressing trust on treatment
lrmt2 = lm(trust ~ treat_rnd, data = dlu, na.action = na.omit)
summary(lrmt2)
```
```{r}
names(summary(lrmt2))
summary(lrmt2)$coefficients
summary(lrmt2)$coefficients[,2]['treat_rnd']
```
```{r}
# Generic function to randomly(pseudo) pick the treatment assignments
coeff_treat_rnd <- function(d) {
  d$treat_rnd = sample(d$treat)
  lmr = lm(trust ~ treat_rnd, data=d, na.action = na.omit)
  return (lmr$coefficients['treat_rnd'])
}

# Trying another randomization
coeff_treat_rnd(dlu)
```
```{r}
# 1K Randomizations
h.distribution.under.sharp.null <- replicate(10000, coeff_treat_rnd(dlu))
h.ate.mean <- mean(h.distribution.under.sharp.null)
paste0("Mean fromm 1k randomizations: ", h.ate.mean)

```

```{r}
# Graph for the estimates
plot(density(h.distribution.under.sharp.null), 
     main = "Density under Sharp Null")

# Adding our original ATE to the plot
abline(v = ate, col = "blue")

# Adding the mean to the plot
abline(v = mean(h.distribution.under.sharp.null), col = 'orange')
```
```{r}
# p value
pv = mean(abs(h.distribution.under.sharp.null) >= abs(ate))
paste0('p value: ', pv)
```
```{r}
# num of assignments that generate an estimated ATE at least as large as the actual
n <- sum(abs(h.distribution.under.sharp.null) >= abs(ate))
paste0("Number of assignments that generate an ATE at least as large as what we got from the experiment: ", n)
```


```{r}
# Standard error
se = sd(h.distribution.under.sharp.null)/sqrt(length(h.distribution.under.sharp.null))
paste0('Standard error: ', se)
                                             
                                            
```
